services:
  mealie-organizer:
    image: ${MEALIE_ORGANIZER_IMAGE:-ghcr.io/thekannen/mealie-organizer}:${MEALIE_ORGANIZER_TAG:-latest}
    container_name: mealie-organizer
    restart: unless-stopped
    env_file:
      - .env
    environment:
      TASK: ${TASK:-webui-server}
      RUN_MODE: ${RUN_MODE:-once}
      TAXONOMY_REFRESH_MODE: ${TAXONOMY_REFRESH_MODE:-merge}
      WEB_BIND_PORT: ${WEB_BIND_PORT:-4820}
    volumes:
      - ./configs:/app/configs
      - ./cache:/app/cache
      - ./logs:/app/logs
      - ./reports:/app/reports
    ports:
      - "${WEB_BIND_PORT:-4820}:${WEB_BIND_PORT:-4820}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
