services:
  cookdex:
    image: ${COOKDEX_IMAGE:-ghcr.io/thekannen/cookdex}:${COOKDEX_TAG:-latest}
    container_name: cookdex
    restart: unless-stopped
    env_file:
      - path: .env
        required: false
    environment:
      TAXONOMY_REFRESH_MODE: ${TAXONOMY_REFRESH_MODE:-merge}
      WEB_BIND_PORT: ${WEB_BIND_PORT:-4820}
    volumes:
      - ./configs:/app/configs
      - ./cache:/app/cache
      - ./logs:/app/logs
      - ./reports:/app/reports
      # Uncomment to mount an SSH key for Direct DB tunnel access:
      # - ~/.ssh/cookdex_mealie:/app/.ssh/cookdex_mealie
    ports:
      - "${WEB_BIND_PORT:-4820}:${WEB_BIND_PORT:-4820}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
